-- Psycards - complete Supabase setup voor gezamenlijke invoer
-- Voer dit uit in Supabase > SQL Editor > New query > Run
-- Bestaande gegevens in de tabellen worden NIET verwijderd.

-- 1. Hoofdvoorraad
create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  name text not null,
  condition text not null default 'NM',
  buy numeric(10,2) not null default 0,
  ask numeric(10,2) not null default 0,
  minimum numeric(10,2) not null default 0,
  status text not null default 'Op voorraad',
  photo text,
  quantity integer not null default 1,
  sold_quantity integer not null default 0,
  sold_price numeric(10,2) not null default 0,
  payment text,
  sold_date timestamptz,
  created_at timestamptz not null default now()
);

alter table public.cards add column if not exists quantity integer not null default 1;
alter table public.cards add column if not exists sold_quantity integer not null default 0;

-- Kolommen die de huidige Psycards-app gebruikt.
alter table public.cards add column if not exists product_type text;
alter table public.cards add column if not exists variant text;

-- 2. Sets
create table if not exists public.psycard_sets (
  id bigint generated by default as identity primary key,
  name text not null,
  language text not null default 'en',
  tcgdex_id text,
  set_code text,
  created_at timestamptz not null default now()
);

-- 3. Bundels
create table if not exists public.bundles (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'Samengesteld',
  ask numeric(10,2) not null default 0,
  sold_price numeric(10,2) not null default 0,
  payment text,
  sold_date timestamptz,
  created_at timestamptz not null default now()
);

-- 4. Kaarten in bundels
create table if not exists public.bundle_items (
  id bigint generated by default as identity primary key,
  bundle_id bigint not null references public.bundles(id) on delete cascade,
  card_id bigint not null references public.cards(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now()
);

-- RLS aan op alle tabellen.
alter table public.cards enable row level security;
alter table public.psycard_sets enable row level security;
alter table public.bundles enable row level security;
alter table public.bundle_items enable row level security;

-- De huidige GitHub Pages-app gebruikt de Supabase anon key.
-- Daarom krijgen apparaten die Psycards openen gezamenlijke lees/schrijftoegang.
drop policy if exists "Psycards gezamenlijke toegang" on public.cards;
create policy "Psycards gezamenlijke toegang" on public.cards
for all to anon using (true) with check (true);

drop policy if exists "Psycards gezamenlijke toegang" on public.psycard_sets;
create policy "Psycards gezamenlijke toegang" on public.psycard_sets
for all to anon using (true) with check (true);

drop policy if exists "Psycards gezamenlijke toegang" on public.bundles;
create policy "Psycards gezamenlijke toegang" on public.bundles
for all to anon using (true) with check (true);

drop policy if exists "Psycards gezamenlijke toegang" on public.bundle_items;
create policy "Psycards gezamenlijke toegang" on public.bundle_items
for all to anon using (true) with check (true);

-- Realtime: meerdere apparaten zien wijzigingen zonder aparte database.
do $$
begin
  begin alter publication supabase_realtime add table public.cards;
  exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.psycard_sets;
  exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.bundles;
  exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.bundle_items;
  exception when duplicate_object then null; end;
end $$;
