-- Voer dit eenmalig uit in Supabase: SQL Editor > New query > Run
create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  name text not null,
  condition text not null default 'NM',
  buy numeric(10,2) not null default 0,
  ask numeric(10,2) not null default 0,
  minimum numeric(10,2) not null default 0,
  status text not null default 'Op voorraad' check (status in ('Op voorraad','Verkocht')),
  photo text,
  quantity integer not null default 1 check (quantity > 0),
  sold_quantity integer not null default 0 check (sold_quantity >= 0),
  sold_price numeric(10,2) not null default 0,
  payment text,
  sold_date timestamptz,
  created_at timestamptz not null default now()
);

-- Werkt ook wanneer de tabel door een eerdere versie al bestaat.
alter table public.cards add column if not exists quantity integer not null default 1;
alter table public.cards add column if not exists sold_quantity integer not null default 0;

alter table public.cards enable row level security;

drop policy if exists "Psycards gezamenlijke toegang" on public.cards;
create policy "Psycards gezamenlijke toegang"
on public.cards for all
to anon
using (true)
with check (true);

do $$
begin
  alter publication supabase_realtime add table public.cards;
exception when duplicate_object then null;
end $$;
